using Microsoft.AspNetCore.Mvc;
using SchoolERP.Net.Services;
using SchoolERP.Net.Models;
using System.Security.Claims;

namespace SchoolERP.Net.Controllers
{
    public class StudentInformationController : Controller
    {
        private readonly IStudentInformationService _studentService;
        private readonly ICompanyService _companyService;
        private readonly IFieldService _fieldService;
        private readonly ISessionService _sessionService;
        private readonly IRouteService _routeService;
        private readonly IRoutePickupPointService _routePickupPointService;
        private readonly IHostelService _hostelService;
        private readonly IClassService _classService;
        private readonly ISectionService _sectionService;
        private readonly IVehicleAssignService _vehicleAssignService;


        public StudentInformationController(IStudentInformationService studentService, ICompanyService companyService, ISessionService sessionService, IFieldService fieldService, IRouteService routeService, IRoutePickupPointService routePickupPointService, IHostelService hostelService, IClassService classService, ISectionService sectionService, IVehicleAssignService vehicleAssignService)
        {
            _studentService = studentService;
            _companyService = companyService;
            _sessionService = sessionService;
            _fieldService = fieldService;
            _routeService = routeService;
            _routePickupPointService = routePickupPointService;
            _hostelService = hostelService;
            _classService = classService;
            _sectionService = sectionService;
            _vehicleAssignService = vehicleAssignService;
        }


        private int GetUserId() => int.TryParse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? User.FindFirst("UserId")?.Value, out var id) ? id : 0;
        private int GetCompanyId() => _companyService.GetUserCurrentCompany(GetUserId()) ?? 0;
        private int GetSessionId() => _sessionService.GetUserCurrentSession(GetUserId()) ?? 0;

        public IActionResult DisableReason()
        {
            var model = new StudentDisableReasonPageViewModel
            {
                Items = _studentService.GetAllDisableReasons(GetCompanyId(), GetSessionId())
            };
            return View(model);
        }

        public IActionResult StudentHouse()
        {
            var model = new StudentHousePageViewModel
            {
                Items = _studentService.GetAllStudentHouses(GetCompanyId(), GetSessionId())
            };
            return View(model);
        }

        public IActionResult StudentCategory()
        {
            var model = new StudentCategoryPageViewModel
            {
                Items = _studentService.GetAllStudentCategories(GetCompanyId(), GetSessionId())
            };
            return View(model);
        }

        public IActionResult StudentAdmission(int? id)
        {
            var companyId = GetCompanyId();
            var sessionId = GetSessionId();
            
            // Fetch all fields to ensure Transport, Hostel, and Guardian categories are included
            var fields = _fieldService.GetAllFields(companyId, sessionId, belongsTo: "students");
            
            if (id.HasValue && id > 0)
            {
                var studentDetails = _studentService.GetStudentDetails(id.Value, companyId, sessionId);
                if (studentDetails.BasicInfo.StudentID > 0)
                {
                    ViewBag.StudentDetails = studentDetails;
                    ViewBag.IsEdit = true;
                }
            }
            
            

            // Fetch lookup data for dropdowns
            ViewBag.Categories = _studentService.GetAllStudentCategories(companyId, sessionId);
            ViewBag.Houses = _studentService.GetAllStudentHouses(companyId, sessionId);
            ViewBag.Routes = _routeService.GetAllRoutes(companyId, sessionId);
            ViewBag.PickupPoints = _routePickupPointService.GetAllRoutePickupPoints(companyId, sessionId);
            ViewBag.Hostels = _hostelService.GetAllHostels(companyId, sessionId);
            ViewBag.VehicleAssignments = _vehicleAssignService.GetAllAssignments(companyId, sessionId);
            ViewBag.Classes = _classService.GetAllClasses(companyId, sessionId);

            // Check if Roll No is Auto Generated
            var autoGenSettings = _fieldService.GetIDAutoGenSettings(companyId, sessionId);
            var studentSettings = autoGenSettings.FirstOrDefault(s => s.EntityType == "Student" && s.IsEnabled);
            bool isRollAutoGenerated = studentSettings != null;
            ViewBag.IsRollAutoGenerated = isRollAutoGenerated;
            if (isRollAutoGenerated)
            {
                ViewBag.RollNoDependencies = studentSettings.FieldsToInclude;
                if (!(ViewBag.IsEdit ?? false))
                {
                    ViewBag.NextRollNo = _studentService.GetNewStudentRollNo(companyId, sessionId);
                }
            }

            return View(fields);
        }

        [HttpGet]
        public IActionResult GetStudentList(int? classId, int? sectionId, string? searchTerm, int? excludeStudentId)
        {
            var companyId = GetCompanyId();
            var sessionId = GetSessionId();
            var students = _studentService.GetStudentList(companyId, sessionId, classId, sectionId, searchTerm);
            
            if (excludeStudentId.HasValue)
            {
                students = students.Where(s => s.StudentID != excludeStudentId.Value).ToList();
            }

            var result = students.Select(s => new { 
                studentID = s.StudentID, 
                fullName = s.FullName, 
                admissionNo = s.AdmissionNo,
                rollNo = s.RollNo
            }).ToList();
            return Json(result);
        }

        [HttpGet]
        [HttpPost]
        public IActionResult Students(int? classId, int? sectionId, string? search)
        {
            var companyId = GetCompanyId();
            var sessionId = GetSessionId();
            
            var model = new StudentListPageViewModel
            {
                Students = _studentService.GetStudentList(companyId, sessionId, classId, sectionId, search),
                SelectedClassId = classId,
                SelectedSectionId = sectionId,
                SearchTerm = search
            };

            ViewBag.Classes = _classService.GetAllClasses(companyId, sessionId);
            if (classId.HasValue)
            {
                ViewBag.Sections = _sectionService.GetSectionsByClass(classId.Value);
            }
            else
            {
                ViewBag.Sections = new List<MstSectionViewModel>();
            }

            return View(model);
        }
        [Route("StudentInformation/Details/{id}")]
        public IActionResult Details(int id)
        {
            var model = _studentService.GetStudentDetails(id, GetCompanyId(), GetSessionId());
            if (model.BasicInfo.StudentID == 0) 
            {
                return Content($"Student record with ID {id} was not found for the current Company/Session.");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult GetStudentDetails(int id)
        {
            var model = _studentService.GetStudentDetails(id, GetCompanyId(), GetSessionId());
            return Json(model);
        }
        [HttpGet]
        public IActionResult GetNextRollNo()
        {
            var query = Request.Query;
            var values = new Dictionary<string, string>();
            foreach (var key in query.Keys)
            {
                values[key] = query[key]!;
            }
            string rollNo = _studentService.GetNewStudentRollNo(GetCompanyId(), GetSessionId(), values);
            return Json(new { rollNo });
        }

        [HttpGet]
        public IActionResult GetNextAdmissionNo()
        {
            string admissionNo = _studentService.GetNextSimpleAdmissionNo(GetCompanyId());
            return Json(new { admissionNo });
        }

        [HttpPost]
        public IActionResult SaveStudent([FromBody] StudentAdmissionUpsertRequest req)
        {
            var res = _studentService.UpsertStudentAdmission(req, GetCompanyId(), GetSessionId(), GetUserId());
            return Json(new { success = res.Success, message = res.Message });
        }

        [HttpGet]
        public IActionResult GetPickupPoints(int routeId)
        {
            var companyId = GetCompanyId();
            var sessionId = GetSessionId();
            var allLinks = _routePickupPointService.GetAllRoutePickupPoints(companyId, sessionId);
            var points = allLinks.Where(l => l.RouteID == routeId && l.IsActive)
                                 .Select(l => new { id = l.PickupPointID, name = l.PickupPointName })
                                 .ToList();
            return Json(points);
        }

        [HttpGet]
        public IActionResult GetHostelRooms(int hostelId)
        {
            var companyId = GetCompanyId();
            var sessionId = GetSessionId();
            var allRooms = _hostelService.GetAllHostelRooms(companyId, sessionId);
            var rooms = allRooms.Where(r => r.HostelID == hostelId && r.IsActive)
                                .Select(r => new { id = r.RoomId, name = r.RoomTitle })
                                .ToList();
            return Json(rooms);
        }

        [HttpGet]
        public IActionResult GetSections(int classId)
        {
            var sections = _sectionService.GetSectionsByClass(classId);
            var result = sections.Where(s => s.IsActive)
                                 .Select(s => new { id = s.SectionID, name = s.SectionName })
                                 .ToList();
            return Json(result);
        }

        [HttpPost]
        public IActionResult DeleteStudent(int id)
        {
            var res = _studentService.DeleteStudent(id, GetUserId());
            return Json(new { success = res.Success, message = res.Message });
        }

        public IActionResult MultiClassStudents()
        {
            return View();
        }

        [HttpGet]
        [HttpPost]
        public IActionResult DisabledStudents(int? classId, int? sectionId, string? search)
        {
            var companyId = GetCompanyId();
            var sessionId = GetSessionId();

            var model = new StudentListPageViewModel
            {
                Students = _studentService.GetDisabledStudentList(companyId, sessionId, classId, sectionId, search),
                SelectedClassId = classId,
                SelectedSectionId = sectionId,
                SearchTerm = search
            };

            ViewBag.Classes = _classService.GetAllClasses(companyId, sessionId);
            if (classId.HasValue)
            {
                ViewBag.Sections = _sectionService.GetSectionsByClass(classId.Value);
            }
            else
            {
                ViewBag.Sections = new List<MstSectionViewModel>();
            }

            return View(model);
        }

        public IActionResult BulkDelete()
        {
            var companyId = GetCompanyId();
            var sessionId = GetSessionId();
            ViewBag.Classes = _classService.GetAllClasses(companyId, sessionId);
            return View();
        }

        [HttpPost]
        public IActionResult BulkDeleteStudents([FromBody] List<int> ids)
        {
            var res = _studentService.BulkDeleteStudents(ids, GetUserId());
            return Json(new { success = res.Success, message = res.Message });
        }
    }
}
