USE [SchoolERP]
GO

/****** Object:  StoredProcedure [dbo].[SP_STUDENT_ADMISSION_UPSERT] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SP_STUDENT_ADMISSION_UPSERT]
(
    @STUDENTID INT = 0,
    @COMPANYID INT,
    @SESSIONID INT,
    @ROLLNO NVARCHAR(50) = NULL,
    @ADMISSIONNO NVARCHAR(50) = NULL,
    @ADMISSIONDATE DATETIME = NULL,
    @CLASSID INT = NULL,
    @SECTIONID INT = NULL,
    @FIRSTNAME NVARCHAR(100) = NULL,
    @MIDDLENAME NVARCHAR(100) = NULL,
    @LASTNAME NVARCHAR(100) = NULL,
    @GENDER NVARCHAR(10) = NULL,
    @DOB DATETIME = NULL,
    @CATEGORYID INT = NULL,
    @RELIGION NVARCHAR(50) = NULL,
    @CASTE NVARCHAR(50) = NULL,
    @MOBILENO NVARCHAR(20) = NULL,
    @EMAIL NVARCHAR(100) = NULL,
    @BLOODGROUP NVARCHAR(10) = NULL,
    @HOUSEID INT = NULL,
    @HEIGHT NVARCHAR(20) = NULL,
    @WEIGHT NVARCHAR(20) = NULL,

    -- BINARY PHOTOS & METADATA
    @STUDENTPHOTO VARBINARY(MAX) = NULL,
    @STUDENTPHOTOTYPE NVARCHAR(50) = NULL,
    @STUDENTPHOTONAME NVARCHAR(255) = NULL,
    @FATHERPHOTO VARBINARY(MAX) = NULL,
    @FATHERPHOTOTYPE NVARCHAR(50) = NULL,
    @FATHERPHOTONAME NVARCHAR(255) = NULL,
    @MOTHERPHOTO VARBINARY(MAX) = NULL,
    @MOTHERPHOTOTYPE NVARCHAR(50) = NULL,
    @MOTHERPHOTONAME NVARCHAR(255) = NULL,
    @GUARDIANPHOTO VARBINARY(MAX) = NULL,
    @GUARDIANPHOTOTYPE NVARCHAR(50) = NULL,
    @GUARDIANPHOTONAME NVARCHAR(255) = NULL,

    -- PARENTS & GUARDIAN DETAILS
    @FATHERNAME NVARCHAR(200) = NULL,
    @FATHERPHONE NVARCHAR(20) = NULL,
    @FATHEROCCUPATION NVARCHAR(100) = NULL,
    @MOTHERNAME NVARCHAR(200) = NULL,
    @MOTHERPHONE NVARCHAR(20) = NULL,
    @MOTHEROCCUPATION NVARCHAR(100) = NULL,
    @IFGUARDIANIS NVARCHAR(50) = NULL,
    @GUARDIANNAME NVARCHAR(200) = NULL,
    @GUARDIANPHONE NVARCHAR(20) = NULL,
    @GUARDIANOCCUPATION NVARCHAR(100) = NULL,
    @GUARDIANRELATION NVARCHAR(100) = NULL,
    @GUARDIANEMAIL NVARCHAR(100) = NULL,

    -- AUTH DETAILS
    @STUDENTUSERNAME NVARCHAR(100) = NULL,
    @STUDENTPASSWORD NVARCHAR(100) = NULL,
    @PARENTUSERNAME NVARCHAR(100) = NULL,
    @PARENTPASSWORD NVARCHAR(100) = NULL,

    -- MAPPING DETAILS
    @CURRENTADDRESS NVARCHAR(MAX) = NULL,
    @PERMANENTADDRESS NVARCHAR(MAX) = NULL,
    @ROUTEID INT = NULL,
    @PICKUPPOINTID INT = NULL,
    @TRANSPORTMONTH NVARCHAR(20) = NULL,
    @HOSTELID INT = NULL,
    @ROOMID INT = NULL,

    -- CUSTOM FIELDS
    @CUSTOMFIELDS TYPE_STUDENTCUSTOMFIELDS READONLY,

    @USERID INT
)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION;
    BEGIN TRY

        DECLARE @STUDENTUSERID INT = NULL;
        DECLARE @PARENTUSERID INT = NULL;
        DECLARE @DONEBYNAME NVARCHAR(50);

        SELECT @DONEBYNAME = ISNULL(USERNAME, 'SYSTEM') FROM TBL_MST_USERS WHERE USERID = @USERID;

        ------------------------------------------------------------------
        -- STEP 1 : USER CREATION & PERMISSION MAPPING
        ------------------------------------------------------------------
        IF @STUDENTID = 0
        BEGIN
            -- 1.1 STUDENT USER
            IF @STUDENTUSERNAME IS NOT NULL AND @STUDENTPASSWORD IS NOT NULL
            BEGIN
                DECLARE @S_SALTBYTES VARBINARY(16) = CRYPT_GEN_RANDOM(16);
                DECLARE @S_HASHBYTES VARBINARY(64) = HASHBYTES('SHA2_512', @STUDENTPASSWORD + CAST(@S_SALTBYTES AS NVARCHAR(MAX)));

                INSERT INTO TBL_MST_USERS (FULLNAME, USERNAME, PASSWORDHASH, PASSWORDSALT, USERTYPEID, COMPANYID, CREATEDBY, ISACTIVE)
                VALUES (ISNULL(@FIRSTNAME, '') + ' ' + ISNULL(@LASTNAME, ''), @STUDENTUSERNAME, 
                        CAST(N'' AS XML).value('xs:base64Binary(sql:variable("@S_HASHBYTES"))', 'NVARCHAR(MAX)'),
                        CAST(N'' AS XML).value('xs:base64Binary(sql:variable("@S_SALTBYTES"))', 'NVARCHAR(MAX)'),
                        (SELECT TOP 1 USERTYPEID FROM TBL_MST_USER_TYPES WHERE TYPENAME = 'Student'), @COMPANYID, @USERID, 1);
                
                SET @STUDENTUSERID = SCOPE_IDENTITY();

                -- Assign Role
                DECLARE @SROLEID INT = (SELECT TOP 1 ROLEID FROM TBL_MST_ROLES WHERE ROLENAME = 'Student');
                IF @SROLEID IS NOT NULL
                BEGIN
                    INSERT INTO TBL_MAP_USER_ROLE (USERID, ROLEID, ASSIGNEDBY, CREATEDBY)
                    VALUES (@STUDENTUSERID, @SROLEID, @USERID, @USERID);

                    -- Copy Permissions from Role to User
                    INSERT INTO tbl_map_user_permissions (UserID, MenuID, PermissionID, IsAllowed, CreatedBy, ModifiedBy)
                    SELECT @STUDENTUSERID, MenuID, PermissionID, 1, @USERID, @USERID
                    FROM tbl_map_role_permissions 
                    WHERE RoleID = @SROLEID AND IsActive = 1 AND IsDelete = 0;
                END
            END

            -- 1.2 PARENT USER
            IF @PARENTUSERNAME IS NOT NULL AND @PARENTPASSWORD IS NOT NULL
            BEGIN
                DECLARE @P_SALTBYTES VARBINARY(16) = CRYPT_GEN_RANDOM(16);
                DECLARE @P_HASHBYTES VARBINARY(64) = HASHBYTES('SHA2_512', @PARENTPASSWORD + CAST(@P_SALTBYTES AS NVARCHAR(MAX)));

                INSERT INTO TBL_MST_USERS (FULLNAME, USERNAME, PASSWORDHASH, PASSWORDSALT, USERTYPEID, COMPANYID, CREATEDBY, ISACTIVE)
                VALUES (ISNULL(@FATHERNAME, 'Parent'), @PARENTUSERNAME, 
                        CAST(N'' AS XML).value('xs:base64Binary(sql:variable("@P_HASHBYTES"))', 'NVARCHAR(MAX)'),
                        CAST(N'' AS XML).value('xs:base64Binary(sql:variable("@P_SALTBYTES"))', 'NVARCHAR(MAX)'),
                        (SELECT TOP 1 USERTYPEID FROM TBL_MST_USER_TYPES WHERE TYPENAME = 'Parent'), @COMPANYID, @USERID, 1);
                
                SET @PARENTUSERID = SCOPE_IDENTITY();

                -- Assign Role
                DECLARE @PROLEID INT = (SELECT TOP 1 ROLEID FROM TBL_MST_ROLES WHERE ROLENAME = 'Parent');
                IF @PROLEID IS NOT NULL
                BEGIN
                    INSERT INTO TBL_MAP_USER_ROLE (USERID, ROLEID, ASSIGNEDBY, CREATEDBY)
                    VALUES (@PARENTUSERID, @PROLEID, @USERID, @USERID);

                    -- Copy Permissions from Role to User
                    INSERT INTO tbl_map_user_permissions (UserID, MenuID, PermissionID, IsAllowed, CreatedBy, ModifiedBy)
                    SELECT @PARENTUSERID, MenuID, PermissionID, 1, @USERID, @USERID
                    FROM tbl_map_role_permissions 
                    WHERE RoleID = @PROLEID AND IsActive = 1 AND IsDelete = 0;
                END
            END
        END

        ------------------------------------------------------------------
        -- STEP 2 : UPSERT STUDENT MASTER
        ------------------------------------------------------------------
        IF @STUDENTID = 0
        BEGIN
            INSERT INTO TBL_MST_STUDENTS
            (
                COMPANYID, SESSIONID, STUDENTUSERID, PARENTUSERID, ROLLNO, ADMISSIONNO, ADMISSIONDATE,
                CLASSID, SECTIONID, FIRSTNAME, MIDDLENAME, LASTNAME, GENDER, DOB,
                CATEGORYID, RELIGION, CASTE, MOBILENO, EMAIL, BLOODGROUP, HOUSEID, HEIGHT, WEIGHT,
                STUDENTPHOTO, STUDENTPHOTOTYPE, STUDENTPHOTONAME,
                FATHERNAME, FATHERPHONE, FATHEROCCUPATION, FATHERPHOTO, FATHERPHOTOTYPE, FATHERPHOTONAME,
                MOTHERNAME, MOTHERPHONE, MOTHEROCCUPATION, MOTHERPHOTO, MOTHERPHOTOTYPE, MOTHERPHOTONAME,
                IFGUARDIANIS, GUARDIANNAME, GUARDIANPHONE, GUARDIANOCCUPATION, GUARDIANRELATION, GUARDIANEMAIL, 
                GUARDIANPHOTO, GUARDIANPHOTOTYPE, GUARDIANPHOTONAME, CREATEDBY, ISDELETE
            )
            VALUES
            (
                @COMPANYID, @SESSIONID, @STUDENTUSERID, @PARENTUSERID, @ROLLNO, @ADMISSIONNO, @ADMISSIONDATE,
                @CLASSID, @SECTIONID, @FIRSTNAME, @MIDDLENAME, @LASTNAME, @GENDER, @DOB,
                @CATEGORYID, @RELIGION, @CASTE, @MOBILENO, @EMAIL, @BLOODGROUP, @HOUSEID, @HEIGHT, @WEIGHT,
                @STUDENTPHOTO, @STUDENTPHOTOTYPE, @STUDENTPHOTONAME,
                @FATHERNAME, @FATHERPHONE, @FATHEROCCUPATION, @FATHERPHOTO, @FATHERPHOTOTYPE, @FATHERPHOTONAME,
                @MOTHERNAME, @MOTHERPHONE, @MOTHEROCCUPATION, @MOTHERPHOTO, @MOTHERPHOTOTYPE, @MOTHERPHOTONAME,
                @IFGUARDIANIS, @GUARDIANNAME, @GUARDIANPHONE, @GUARDIANOCCUPATION, @GUARDIANRELATION, @GUARDIANEMAIL, 
                @GUARDIANPHOTO, @GUARDIANPHOTOTYPE, @GUARDIANPHOTONAME, @USERID, 0
            );
            SET @STUDENTID = SCOPE_IDENTITY();
        END
        ELSE
        BEGIN
            UPDATE TBL_MST_STUDENTS SET
                ROLLNO = @ROLLNO, ADMISSIONNO = @ADMISSIONNO, ADMISSIONDATE = @ADMISSIONDATE,
                CLASSID = @CLASSID, SECTIONID = @SECTIONID, FIRSTNAME = @FIRSTNAME, LASTNAME = @LASTNAME,
                GENDER = @GENDER, DOB = @DOB, MOBILENO = @MOBILENO, EMAIL = @EMAIL,
                STUDENTPHOTO = ISNULL(@STUDENTPHOTO, STUDENTPHOTO), STUDENTPHOTOTYPE = ISNULL(@STUDENTPHOTOTYPE, STUDENTPHOTOTYPE),
                STUDENTPHOTONAME = ISNULL(@STUDENTPHOTONAME, STUDENTPHOTONAME),
                FATHERNAME = @FATHERNAME, FATHERPHONE = @FATHERPHONE, FATHERPHOTO = ISNULL(@FATHERPHOTO, FATHERPHOTO),
                FATHERPHOTOTYPE = ISNULL(@FATHERPHOTOTYPE, FATHERPHOTOTYPE), FATHERPHOTONAME = ISNULL(@FATHERPHOTONAME, FATHERPHOTONAME),
                MOTHERNAME = @MOTHERNAME, MOTHERPHONE = @MOTHERPHONE, MOTHERPHOTO = ISNULL(@MOTHERPHOTO, MOTHERPHOTO),
                MOTHERPHOTOTYPE = ISNULL(@MOTHERPHOTOTYPE, MOTHERPHOTOTYPE), MOTHERPHOTONAME = ISNULL(@MOTHERPHOTONAME, MOTHERPHOTONAME),
                GUARDIANPHOTO = ISNULL(@GUARDIANPHOTO, GUARDIANPHOTO),
                GUARDIANPHOTOTYPE = ISNULL(@GUARDIANPHOTOTYPE, GUARDIANPHOTOTYPE),
                GUARDIANPHOTONAME = ISNULL(@GUARDIANPHOTONAME, GUARDIANPHOTONAME),
                MODIFIEDON = GETDATE(), MODIFIEDBY = @USERID
            WHERE STUDENTID = @STUDENTID;
        END

        ------------------------------------------------------------------
        -- STEP 3 : STUDENT HISTORY
        ------------------------------------------------------------------
        INSERT INTO TBL_MST_STUDENTS_HISTORY
        (
            STUDENTID, COMPANYID, SESSIONID, ROLLNO, ADMISSIONNO, FIRSTNAME, LASTNAME, MOBILENO,
            STUDENTPHOTO, STUDENTPHOTOTYPE, STUDENTPHOTONAME, FATHERPHOTO, FATHERPHOTOTYPE, FATHERPHOTONAME,
            MOTHERPHOTO, MOTHERPHOTOTYPE, MOTHERPHOTONAME, GUARDIANPHOTO, GUARDIANPHOTOTYPE, GUARDIANPHOTONAME,
            ISACTIVE, ISDELETE, CREATEDON, CREATEDBY, UPDATEDELETEFLAG, DONEON, DONEBY, DONEBYNAME
        )
        SELECT 
            STUDENTID, COMPANYID, SESSIONID, ROLLNO, ADMISSIONNO, FIRSTNAME, LASTNAME, MOBILENO,
            STUDENTPHOTO, STUDENTPHOTOTYPE, STUDENTPHOTONAME, FATHERPHOTO, FATHERPHOTOTYPE, FATHERPHOTONAME,
            MOTHERPHOTO, MOTHERPHOTOTYPE, MOTHERPHOTONAME, GUARDIANPHOTO, GUARDIANPHOTOTYPE, GUARDIANPHOTONAME,
            ISACTIVE, ISDELETE, CREATEDON, CREATEDBY, 'SYNC', GETUTCDATE(), @USERID, @DONEBYNAME
        FROM TBL_MST_STUDENTS WHERE STUDENTID = @STUDENTID;

        ------------------------------------------------------------------
        -- STEP 4 : MODULE SYNC (ADDRESS, TRANSPORT, HOSTEL, CUSTOM FIELDS)
        ------------------------------------------------------------------
        -- Address
        DELETE FROM TBL_STUDENT_ADDRESS WHERE STUDENTID = @STUDENTID;
        IF @CURRENTADDRESS IS NOT NULL INSERT INTO TBL_STUDENT_ADDRESS (COMPANYID, SESSIONID, STUDENTID, ADDRESSTYPE, ADDRESSDETAILS, CREATEDBY) VALUES (@COMPANYID, @SESSIONID, @STUDENTID, 'Current', @CURRENTADDRESS, @USERID);
        IF @PERMANENTADDRESS IS NOT NULL INSERT INTO TBL_STUDENT_ADDRESS (COMPANYID, SESSIONID, STUDENTID, ADDRESSTYPE, ADDRESSDETAILS, CREATEDBY) VALUES (@COMPANYID, @SESSIONID, @STUDENTID, 'Permanent', @PERMANENTADDRESS, @USERID);

        -- Transport
        DELETE FROM TBL_STUDENT_TRANSPORTMAPPING WHERE STUDENTID = @STUDENTID;
        IF @ROUTEID IS NOT NULL INSERT INTO TBL_STUDENT_TRANSPORTMAPPING (COMPANYID, SESSIONID, STUDENTID, ROUTEID, PICKUPPOINTID, STARTMONTH, CREATEDBY) VALUES (@COMPANYID, @SESSIONID, @STUDENTID, @ROUTEID, @PICKUPPOINTID, @TRANSPORTMONTH, @USERID);

        -- Hostel
        DELETE FROM TBL_STUDENT_HOSTELMAPPING WHERE STUDENTID = @STUDENTID;
        IF @HOSTELID IS NOT NULL INSERT INTO TBL_STUDENT_HOSTELMAPPING (COMPANYID, SESSIONID, STUDENTID, HOSTELID, ROOMID, CREATEDBY) VALUES (@COMPANYID, @SESSIONID, @STUDENTID, @HOSTELID, @ROOMID, @USERID);

        -- Custom Fields
        DELETE FROM TBL_STUDENT_CUSTOMFIELDVALUES WHERE STUDENTID = @STUDENTID;
        INSERT INTO TBL_STUDENT_CUSTOMFIELDVALUES (STUDENTID, FIELDID, FIELDVALUE, CREATEDBY)
        SELECT @STUDENTID, FIELDID, FIELDVALUE, @USERID FROM @CUSTOMFIELDS;

        COMMIT TRANSACTION;
        SELECT @STUDENTID AS RESULT, 'ADMISSION SUCCESSFUL. STUDENT ID: ' + CAST(@STUDENTID AS NVARCHAR(10)) AS MESSAGE;

    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        SELECT 0 AS RESULT, ERROR_MESSAGE() AS MESSAGE;
    END CATCH
END
